config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
  get 'session/new'
  get 'main/index'
  get 'dark', to: 'session#dark'
  get 'light', to: 'session#light'

  resources :sources
  resources :categories
  resources :topics
  resources :resources
  resources :session, only: [:new, :create, :destroy]

  get '/check.txt', to: proc {[200, {}, ['it_works']]}
  get '/:id', to: 'main#index'
end

app/models/topic.rb
# frozen_string_literal: true

class Topic < ApplicationRecord
  has_many :resources
  belongs_to :category

  def long_title
    "#{category.nil? ? 'Other' : category.title}: #{title}"
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authentication_required!

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description, :category_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= simple_form_for(@topic) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>
  <div class="form-inputs">
    <%= f.input :description %>
  </div>
  <div class="form-inputs">
    <%= f.association :category, label_method: :title, value_method: :id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<%= content_for :body do %>
    <h1>Editing Topic</h1>

    <%= render 'form', topic: @topic %>

    <%= link_to 'Show', @topic %> |
    <%= link_to 'Back', topics_path %>
<% end %>

<%= render 'layouts/small_page' %>

app/views/topics/index.html.erb
<%= content_for :body do %>
  <p id="notice"><%= notice %></p>
      <h1>Topics</h1>

      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @topics.each do |topic| %>
            <tr>
              <td><%= topic.long_title %></td>
              <td><%= link_to 'Show', topic, class: 'btn btn-sm btn-outline-primary' %></td>
              <td><%= link_to 'Edit', edit_topic_path(topic), class: 'btn btn-sm btn-outline-warning' %></td>
              <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Topic', new_topic_path, class: 'btn btn-sm btn-outline-primary' %>
<% end %>

<%= render 'layouts/small_page' %>

app/views/topics/new.html.erb
<%= content_for :body do %>
  <div class="row">
    <div class="col-md-4 mx-auto">
      <h1>New Topic</h1>

      <%= render 'form', topic: @topic %>
  <%= link_to 'Back', topics_path %>
    </div>
  </div>
<% end %>

<%= render 'layouts/small_page' %>

app/views/topics/show.html.erb
<%= content_for :body do %>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @topic.title %>
  </p>

  <%= link_to 'Edit', edit_topic_path(@topic) %> |
  <%= link_to 'Back', topics_path %>
<% end %>

<%= render 'layouts/small_page' %>