config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
  get 'session/new'
  get 'main/index'
  get 'dark', to: 'session#dark'
  get 'light', to: 'session#light'

  resources :sources
  resources :categories
  resources :topics
  resources :resources
  resources :session, only: [:new, :create, :destroy]

  get '/check.txt', to: proc {[200, {}, ['it_works']]}
  get '/:id', to: 'main#index'
end

app/views/resources/_form.html.erb
    <%= simple_form_for(@resource) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :title %>
        <%= f.input :url %>
        <%= f.input :description %>
        <%= f.association :topic, label_method: :long_title, value_method: :id %>
        <%= f.association :source, label_method: :title, value_method: :id %>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>

app/views/resources/edit.html.erb
<%= content_for :body do %>
    <h1>Editing Resource</h1>

    <%= render 'form', resource: @resource %>

    <%= link_to 'Show', @resource %> |
    <%= link_to 'Back', resources_path %>
<% end %>

<%= render 'layouts/small_page' %>

app/views/resources/index.html.erb
<%= content_for :body do %>
    <p id="notice"><%= notice %></p>

    <h1>Resources</h1>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @resources.each do |resource| %>
          <tr>
            <td><%= link_to resource.title, resource.url, target: "_blank" %></td>
            <td><%= resource.description %></td>
            <td><%= link_to 'Show', resource, class: 'btn btn-sm btn-outline-primary' %></td>
            <td><%= link_to 'Edit', edit_resource_path(resource), class: 'btn btn-sm btn-outline-warning' %></td>
            <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New', new_resource_path, class: 'btn btn-sm btn-outline-primary' %>
<% end %>

<%= render 'layouts/small_page' %>

app/views/resources/new.html.erb
<%= content_for :body do %>
    <h1>New Resource</h1>

    <%= render 'form', resource: @resource %>
    <%= link_to 'Back', resources_path %>
<% end %>

<%= render 'layouts/small_page' %>

app/views/resources/show.html.erb
<%= content_for :body do %>
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Title:</strong>
      <%= @resource.title %>
    </p>

    <p>
      <strong>Url:</strong>
      <%= @resource.url %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @resource.description %>
    </p>
    <p>
      <strong>Topic:</strong>
      <%= @resource.topic.long_title unless @resource.topic.nil? %>
    </p>
    <p>
      <strong>Source:</strong>
      <%= @resource.source.title unless @resource.source.nil? %>
    </p>

    <%= link_to 'Edit', edit_resource_path(@resource) %> |
    <%= link_to 'Back', resources_path %>
<% end %>

<%= render 'layouts/small_page' %>