config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
  get 'session/new'
  get 'main/index'
  get 'dark', to: 'session#dark'
  get 'light', to: 'session#light'

  resources :sources
  resources :categories
  resources :topics
  resources :resources
  resources :session, only: [:new, :create, :destroy]

  get '/check.txt', to: proc {[200, {}, ['it_works']]}
  get '/:id', to: 'main#index'
end

app/views/layouts/_footer.html.erb
        <div class="<%= common_sizing %> mb-3 <%= style_headerfooter %> rounded-bottom d-flex justify-content-center py-1">
        <a href="mailto:alan@alanvardy.com" class="btn btn-sm btn-outline-grey0 mx-4"><i class="fas fa-envelope mr-1"></i> Email</a>
        <% if !admin? %>
            <%= link_to(session_new_path, html_options = { class: "btn btn-sm btn-outline-grey0" }) do %>
                <i class="fas fa-lock mr-1"></i> Admin
            <% end %>
        <% end %>
        <a href="https://www.alanvardy.com/" class="btn btn-sm btn-outline-grey0 mx-4"><i class="fas fa-sitemap mr-1"></i> Site</a>
        <%= link_to(change_mode_path, html_options = { class: "btn btn-sm btn-outline-grey0" }) do %>
            <i class="fas fa-lightbulb"></i> <%= change_mode_name %>
        <% end %>
        </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">RR</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sources
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to 'New', new_source_path, class: 'dropdown-item' %>
        <%= link_to 'All', sources_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to 'New', new_category_path, class: 'dropdown-item' %>
        <%= link_to 'All', categories_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Topics
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to 'New', new_topic_path, class: 'dropdown-item' %>
        <%= link_to 'All', topics_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Resources
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to 'New', new_resource_path, class: 'dropdown-item' %>
        <%= link_to 'All', resources_path, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>

      <div class="nav-item">
      <%= link_to 'Log out', session_path('logout'), method: :delete, class: 'btn btn-outline-info ml-3' %>
      </div>
  </div>
</nav>

app/views/layouts/_popover_script.html.erb
<script>
$(document).ready(function(){
  $('[data-toggle="popover"]').popover();
});
</script>

app/views/layouts/_small_page.html.erb
<div class="my-5 p-3 rounded bg-grey0 col-12 col-lg-6 offset-lg-3">
    <%= yield :body %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Resource</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= style_background %>">
  <%= render 'layouts/navbar' if admin? %>
  <div class="container-fluid">
    <div class="row">
      <%= yield %>
    </div>
  </div>
  </body>
</html>